# Generated by Django 5.2.7 on 2025-12-01 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_department_work_end_time_department_work_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
